let bookings=[],account=null,customers=[],team=[],drivers=[];
let role='owner',page='overview',query='',filter='All',bookingScope='mine';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'Not recorded':'₹'+Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
const paid=b=>(b.payments||[]).reduce((n,p)=>n+p.amount,0),due=b=>b.total==null?null:Math.round((b.total-paid(b))*100)/100;
const date=s=>s?new Date(s+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'Date not recorded';
const visible=()=>bookings.filter(b=>role!=='employee'||(page==='bookings'&&bookingScope==='all')||b.isMine);
const financialBookings=()=>bookings.filter(b=>b.financialVisible&&b.status!=='Cancelled');
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3500)}
function navigation(){const tabs=['customer','driver'].includes(role)?[['bookings','◇',role==='driver'?'Assigned trips':'My bookings']]:[['overview','▦','Overview'],['bookings','◇','Bookings'],['payments','₹','Payments'],['calendar','▦','Calendar'],...(role==='owner'?[['team','♧','Team & access']]:[])];for(const target of ['#desktop-nav','#mobile-nav']){$(target).innerHTML=tabs.map(([id,icon,label])=>`<button data-page="${id}" class="${page===id?'active':''}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');$(target).querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;query='';filter='All';render()})}$('#role-label').textContent=role[0].toUpperCase()+role.slice(1)+' workspace';$('#crumb').textContent=tabs.find(t=>t[0]===page)?.[2]||'Overview'}
function card(b){return `<article class="booking"><div class="booking-top"><span class="id">${escape(b.id)} · ${escape(b.purpose)}</span><span class="badge ${b.status.toLowerCase()}">${escape(b.status)}</span></div><h3>${escape(b.name)}</h3><div class="meta">${date(b.date)} · ${escape(b.time||'Time not recorded')} &nbsp; / &nbsp; ${escape(b.car||'Car not recorded')}</div><div class="route"><span>${escape(b.from)}</span><span>→</span><span>${escape(b.to||'Drop not recorded')}</span></div><div class="booking-foot"><div><small>Agreed fare</small><strong>${b.financialVisible?money(b.total):'—'}</strong></div><div><small>Balance due</small><strong>${b.financialVisible?money(due(b)):'—'}</strong></div><button data-detail="${escape(b.id)}">View booking ↗</button></div></article>`}
function bindDetails(){document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail))}
function stats(){const list=financialBookings();return `<div class="stats">${[['Upcoming trips',list.filter(b=>['Confirmed','Pending'].includes(b.status)).length,'Confirmed & awaiting confirmation','↗'],['Payments received',money(list.reduce((n,b)=>n+paid(b),0)),'Across your bookings','₹'],['Balance to collect',money(list.reduce((n,b)=>n+due(b),0)),list.some(b=>b.total==null)?'Known fares only; some fares are missing':'Outstanding customer payments','◷']].map(([label,value,sub,icon])=>`<div class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><strong>${value}</strong><small>${sub}</small></div>`).join('')}</div>`}
const art=`<div class="journey-art" aria-hidden="true"><svg viewBox="0 0 420 240" fill="none"><circle cx="246" cy="127" r="104" fill="#214e40"/><circle cx="246" cy="127" r="78" stroke="#50745b" stroke-dasharray="3 9"/><path d="M23 189C126 236 152 21 240 63S294 206 415 139" stroke="#a7bc84" stroke-width="2" stroke-dasharray="7 7"/><circle cx="106" cy="156" r="7" fill="#dbe8b3"/><path d="M324 89C340 67 349 59 349 48A25 25 0 0 0 299 48C299 60 312 77 324 89Z" fill="#dbe8b3"/><circle cx="324" cy="48" r="8" fill="#214e40"/><g transform="translate(170 106) rotate(-12)"><rect x="0" y="7" width="113" height="49" rx="14" fill="#e1e6d3"/><path d="M28 7L42-10H78L93 7" fill="#c3cdb4"/><path d="M42-6H76L85 7H33Z" fill="#426054"/><rect x="6" y="21" width="12" height="7" rx="2" fill="#fbf0bc"/><rect x="96" y="21" width="12" height="7" rx="2" fill="#fbf0bc"/><rect x="33" y="29" width="48" height="11" rx="5" fill="#788e77"/><circle cx="23" cy="55" r="11" fill="#102c25"/><circle cx="90" cy="55" r="11" fill="#102c25"/></g></svg></div>`;
function render(){navigation();let title=page==='calendar'?'Your fleet calendar.':page==='overview'?'A good day to go places.':page==='payments'?'Every payment, in view.':page==='team'?'Your people. Your permissions.':role==='customer'?'Your next journey awaits.':'Your booking desk.';$('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">RSS TRAVELS / ${role==='customer'?'CUSTOMER PORTAL':'BOOKING DESK'}</p><h1>${title}</h1><p class="subtitle">${role==='customer'?'Welcome, '+escape(account.name)+'. Your trip details, all in one place.':'A little less paperwork. A lot more peace of mind.'}</p></div>${['owner','employee'].includes(role)&&!['team','calendar'].includes(page)?'<button class="primary" id="new-booking">＋ New booking</button>':''}</div>`;
if(page==='overview'){$('#content').innerHTML+=`<section class="hero"><div class="hero-copy"><p class="eyebrow">ON THE HORIZON</p><h2>Good journeys begin<br>with a little planning.</h2><p>You have <strong>${visible().filter(b=>['Pending','Confirmed'].includes(b.status)).length} upcoming trips</strong>. Let’s get them ready.</p></div>${art}</section>${stats()}<div class="section-head"><div><h2>Upcoming journeys</h2><p>Your next departures, at a glance.</p></div><button class="text-btn" id="view-all">All bookings →</button></div><div class="booking-grid">${visible().filter(b=>['Pending','Confirmed'].includes(b.status)).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4).map(card).join('')||'<div class="empty">No upcoming trips. Create your first booking.</div>'}</div>`;$('#view-all').onclick=()=>{page='bookings';render()}}
if(page==='bookings'||page==='payments'){if(page==='payments')$('#content').innerHTML+=stats();$('#content').innerHTML+=`${role==='customer'?'<p class="info">Your bookings and payment history. Contact RSS Travels for changes to your trip.</p>':''}${role==='employee'&&page==='bookings'?`<label>Show bookings<select id="booking-scope"><option value="mine" ${bookingScope==='mine'?'selected':''}>My bookings</option><option value="all" ${bookingScope==='all'?'selected':''}>All bookings · trip details only</option></select></label>`:''}<div class="tools"><input id="search" aria-label="Search bookings" placeholder="Search name, destination or booking ID…" value="${escape(query)}"><select id="filter" aria-label="Filter bookings">${['All','Confirmed','Pending','In progress','Completed','Cancelled'].map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="booking-grid" id="results"></div>`;results();if($('#booking-scope'))$('#booking-scope').onchange=e=>{bookingScope=e.target.value;results()};$('#search').oninput=e=>{query=e.target.value;results()};$('#filter').onchange=e=>{filter=e.target.value;results()}}
if(page==='team')renderTeam();if(page==='calendar')renderCalendar();
if($('#new-booking'))$('#new-booking').onclick=newBooking;bindDetails()}
function results(){const list=visible().filter(b=>(filter==='All'||b.status===filter)&&(page!=='payments'||((due(b)>0||b.total==null)&&b.status!=='Cancelled'))&&`${b.name} ${b.from} ${b.to} ${b.id}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.date.localeCompare(b.date));$('#results').innerHTML=list.map(card).join('')||'<div class="empty">No bookings match this view.</div>';bindDetails()}
function openModal(html){$('#modal-body').innerHTML=html;$('#modal').showModal();$('#close-modal').onclick=()=>$('#modal').close()}
function modalHead(title){return `<div class="dialog-head"><h2>${title}</h2><button class="close" id="close-modal" aria-label="Close dialog">×</button></div>`}
function newBooking(){bookingForm()}
function bookingForm(b=null){
if(!['owner','employee'].includes(role))return;
const fields=[['name','Customer name','text'],['phone','Contact number','tel'],['secondary','Secondary contact','tel'],['car','Car / registration','text'],['from','Pickup location','text'],['to','Drop location','text'],['date','Travel date','date'],['time','Pickup time','time'],['purpose','Purpose','text'],['total','Agreed fare (₹)','number']];
openModal(`${modalHead(b?'Update booking':'Plan a new journey')}<p class="info">${b?'Existing payments and the booking creator stay unchanged. Blank imported details may be filled in here.':'Bookings are attributed to your signed-in account.'}</p><form id="booking-form"><div class="fields">${!b?`<label class="wide">Customer account (optional)<select name="customerEmail"><option value="">No customer login linked</option>${customers.map(c=>`<option value="${escape(c.email)}">${escape(c.name)}</option>`).join('')}</select></label>`:''}${fields.map(([name,label,type])=>`<label>${label}<input name="${name}" type="${type}" value="${escape(b?.[name]??'')}" ${name==='name'||name==='date'||(!b&&name!=='secondary')?'required':''} ${type==='number'?'min="0" max="10000000" step="0.01"':''} ${type==='tel'?'minlength="7" maxlength="20"':type==='text'?'maxlength="120"':''}></label>`).join('')}<label class="wide">Assigned driver<select name="driverId"><option value="">Not assigned</option>${drivers.map(d=>`<option value="${escape(d.id)}" ${b?.driverId===d.id?'selected':''}>${escape(d.name)}</option>`).join('')}</select></label>${!b?'<label>Advance received (₹)<input type="number" name="advance" required value="0" min="0" max="10000000" step="0.01"></label><label>Advance payment mode<select name="mode"><option>UPI</option><option>Cash</option><option>Bank transfer</option></select></label>':''}</div><p class="error" id="form-error" role="alert"></p><div class="form-actions"><button class="primary">${b?'Save changes':'Create booking'} →</button></div></form>`);
const requestId=crypto.randomUUID();$('#booking-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));for(const key of ['phone','secondary'])if(f[key]&&!/^[0-9+ ()-]{7,20}$/.test(f[key])){$('#form-error').textContent=(key==='phone'?'Contact number':'Secondary contact')+' must contain 7–20 valid characters.';return}f.total=f.total===''?null:Number(f.total);if(!b){f.advance=Number(f.advance);f.requestId=requestId}else f.version=b.version;const btn=e.target.querySelector('button');btn.disabled=true;try{await api(b?'/api/bookings/'+encodeURIComponent(b.id)+'/update':'/api/bookings',f);$('#modal').close();await refresh();toast(b?'Booking updated':'Booking saved')}catch(error){$('#form-error').textContent=error.message}finally{btn.disabled=false}};
}
function detail(id){
const b=bookings.find(b=>b.id===id);if(!b)return;
const finance=b.financialVisible;
openModal(`${modalHead(escape(b.id))}<span class="badge">${escape(b.status)}</span><h3>${escape(b.name)}</h3><div class="detail-route">${escape(b.from)} → ${escape(b.to||'Drop not recorded')}</div><div class="detail-grid">${[['Departure',date(b.date)+' · '+(b.time||'Time not recorded')],['Car',b.car||'Not recorded'],['Driver',b.driverName||'Not assigned'],['Contact',b.phone||'Not recorded'],['Secondary contact',b.secondary||'Not recorded'],...(finance?[['Agreed fare',money(b.total)],['Payments received',money(paid(b))],['Receipt',b.receipt||'Not recorded']]:[])].map(([label,value])=>`<div><small>${label}</small><strong>${escape(value)}</strong></div>`).join('')}</div>${b.canEdit?'<button class="primary" id="edit-booking">Update booking</button>':''}<p class="info">Trip actions are available only on the travel date, using India time.</p>${b.canStart?'<button class="primary" id="start-trip">Start trip</button>':''}${b.canComplete?'<button class="primary" id="complete-trip">End trip</button>':''}${b.startedAt?`<p>Started: ${escape(new Date(b.startedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}))} IST</p>`:''}${b.completedAt?`<p>Completed: ${escape(new Date(b.completedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}))} IST</p>`:''}${finance?`<div class="balance"><span>Remaining balance</span><strong>${money(due(b))}</strong></div><h3>Payment history</h3>${b.payments.map(p=>`<div class="payment"><div>${escape(p.mode)}<small>${date(p.date)} · ${escape(p.by)}</small></div><strong>${money(p.amount)}</strong></div>`).join('')||'<p>No payments recorded.</p>'}${b.canPay&&due(b)>0&&b.status!=='Cancelled'?`<form id="payment-form" class="payment-form"><label>Amount (₹)<input name="amount" type="number" required min="0.01" max="${due(b)}" step="0.01"></label><label>Payment mode<select name="mode"><option>UPI</option><option>Cash</option><option>Bank transfer</option></select></label><button class="primary">Save payment</button></form>`:''}`:''}`);
if($('#edit-booking'))$('#edit-booking').onclick=()=>bookingForm(b);
for(const action of ['start','complete'])if($('#'+action+'-trip'))$('#'+action+'-trip').onclick=async e=>{e.target.disabled=true;try{await api('/api/bookings/'+encodeURIComponent(id)+'/trip',{action,version:b.version});await refresh();detail(id);toast(action==='start'?'Trip started':'Trip completed')}catch(error){toast(error.message);e.target.disabled=false}};
if($('#payment-form')){const requestId=crypto.randomUUID();$('#payment-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const btn=e.target.querySelector('button');btn.disabled=true;try{await api('/api/bookings/'+encodeURIComponent(id)+'/payments',{...f,amount:Number(f.amount),requestId});await refresh();detail(id)}catch(error){toast(error.message);btn.disabled=false}}}
}
let calendarMonth=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Kolkata'}));calendarMonth.setDate(1);
function renderCalendar(){
const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth(),days=new Date(year,month+1,0).getDate(),offset=new Date(year,month,1).getDay();
$('#content').innerHTML+=`<div class="section-head"><button id="prev-month" class="text-btn">← Previous</button><h2>${calendarMonth.toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</h2><button id="next-month" class="text-btn">Next →</button></div><p class="info">All team bookings. Counts use the car name or registration as entered. Cancelled trips are excluded; unspecified cars are listed separately.</p><div class="calendar-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<strong>${x}</strong>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const day=year+'-'+String(month+1).padStart(2,'0')+'-'+String(i+1).padStart(2,'0');const trips=bookings.filter(b=>b.date===day&&b.status!=='Cancelled');const cars=new Set(trips.filter(b=>b.car).map(b=>b.car.trim().toLowerCase()));const missing=trips.filter(b=>!b.car).length;return `<button class="calendar-day" data-day="${day}"><strong>${i+1}</strong><small>${cars.size} cars booked</small>${trips.length?`<small>${trips.length} trips${missing?' · '+missing+' car unspecified':''}</small>`:''}</button>`}).join('')}</div><div id="day-bookings" class="booking-grid"></div>`;
$('#prev-month').onclick=()=>{calendarMonth.setMonth(month-1);render()};$('#next-month').onclick=()=>{calendarMonth.setMonth(month+1);render()};document.querySelectorAll('[data-day]').forEach(btn=>btn.onclick=()=>{$('#day-bookings').innerHTML=bookings.filter(b=>b.date===btn.dataset.day&&b.status!=='Cancelled').map(card).join('')||'<p>No bookings on this day.</p>';bindDetails()});
}
