const KEY='rss-travels-prototype-v1';
const seed=[
 {id:'RSS-1001',customerId:'demo-customer',name:'Aarav Sharma',phone:'9000000001',secondary:'',car:'BMW',from:'Civil Lines, Prayagraj',to:'Varanasi',date:'2026-11-15',time:'09:00',purpose:'Wedding',total:18000,status:'Confirmed',payments:[{amount:5000,mode:'UPI',date:'2026-10-04',by:'Owner'}]},
 {id:'RSS-1002',customerId:'other-customer',name:'Meera Verma',phone:'9000000002',secondary:'',car:'Innova Crysta',from:'Jhunsi, Prayagraj',to:'Lucknow',date:'2026-11-18',time:'07:30',purpose:'Airport transfer',total:12000,status:'Confirmed',payments:[{amount:3000,mode:'Cash',date:'2026-10-04',by:'Owner'}]},
 {id:'RSS-1003',customerId:'third-customer',name:'Rohan Singh',phone:'9000000003',secondary:'',car:'BMW',from:'Naini, Prayagraj',to:'Bhadohi',date:'2026-11-21',time:'10:00',purpose:'Wedding',total:16000,status:'Pending',payments:[]},
 {id:'RSS-1004',customerId:'demo-customer',name:'Aarav Sharma',phone:'9000000001',secondary:'',car:'Innova Crysta',from:'Prayagraj',to:'Pratapgarh',date:'2026-09-28',time:'08:00',purpose:'Family trip',total:8500,status:'Completed',payments:[{amount:8500,mode:'UPI',date:'2026-09-28',by:'Owner'}]}
];
let bookings;try{bookings=JSON.parse(localStorage.getItem(KEY))||structuredClone(seed);if(!Array.isArray(bookings))throw Error();}catch{bookings=structuredClone(seed)}
let role='owner',page='overview',query='',filter='All';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₹'+Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
const paid=b=>b.payments.reduce((n,p)=>n+p.amount,0),due=b=>Math.round((b.total-paid(b))*100)/100;
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
const visible=()=>bookings.filter(b=>role!=='customer'||b.customerId==='demo-customer');
function save(){try{localStorage.setItem(KEY,JSON.stringify(bookings));return true}catch{toast('Browser storage unavailable. Changes last only this session.');return false}}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3500)}
function navigation(){const tabs=role==='customer'?[['bookings','◇','My bookings']]:[['overview','▦','Overview'],['bookings','◇','Bookings'],['payments','₹','Payments'],...(role==='owner'?[['team','♧','Team & access']]:[])];for(const target of ['#desktop-nav','#mobile-nav']){$(target).innerHTML=tabs.map(([id,icon,label])=>`<button data-page="${id}" class="${page===id?'active':''}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');$(target).querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;query='';filter='All';render()})}$('#role-label').textContent=role[0].toUpperCase()+role.slice(1)+' workspace';$('#crumb').textContent=tabs.find(t=>t[0]===page)?.[2]||'Overview'}
function card(b){return `<article class="booking"><div class="booking-top"><span class="id">${escape(b.id)} · ${escape(b.purpose)}</span><span class="badge ${b.status.toLowerCase()}">${escape(b.status)}</span></div><h3>${escape(b.name)}</h3><div class="meta">${date(b.date)} · ${escape(b.time)} &nbsp; / &nbsp; ${escape(b.car)}</div><div class="route"><span>${escape(b.from)}</span><span>→</span><span>${escape(b.to)}</span></div><div class="booking-foot"><div><small>Agreed fare</small><strong>${money(b.total)}</strong></div><div><small>Balance due</small><strong>${money(due(b))}</strong></div><button data-detail="${escape(b.id)}">View booking ↗</button></div></article>`}
function bindDetails(){document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail))}
function stats(){const list=visible().filter(b=>b.status!=='Cancelled');return `<div class="stats">${[['Upcoming trips',list.filter(b=>['Confirmed','Pending'].includes(b.status)).length,'Confirmed & awaiting confirmation','↗'],['Payments received',money(list.reduce((n,b)=>n+paid(b),0)),'Across sample bookings','₹'],['Balance to collect',money(list.reduce((n,b)=>n+due(b),0)),'Outstanding customer payments','◷']].map(([label,value,sub,icon])=>`<div class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><strong>${value}</strong><small>${sub}</small></div>`).join('')}</div>`}
const art=`<div class="journey-art" aria-hidden="true"><svg viewBox="0 0 420 240" fill="none"><circle cx="246" cy="127" r="104" fill="#214e40"/><circle cx="246" cy="127" r="78" stroke="#50745b" stroke-dasharray="3 9"/><path d="M23 189C126 236 152 21 240 63S294 206 415 139" stroke="#a7bc84" stroke-width="2" stroke-dasharray="7 7"/><circle cx="106" cy="156" r="7" fill="#dbe8b3"/><path d="M324 89C340 67 349 59 349 48A25 25 0 0 0 299 48C299 60 312 77 324 89Z" fill="#dbe8b3"/><circle cx="324" cy="48" r="8" fill="#214e40"/><g transform="translate(170 106) rotate(-12)"><rect x="0" y="7" width="113" height="49" rx="14" fill="#e1e6d3"/><path d="M28 7L42-10H78L93 7" fill="#c3cdb4"/><path d="M42-6H76L85 7H33Z" fill="#426054"/><rect x="6" y="21" width="12" height="7" rx="2" fill="#fbf0bc"/><rect x="96" y="21" width="12" height="7" rx="2" fill="#fbf0bc"/><rect x="33" y="29" width="48" height="11" rx="5" fill="#788e77"/><circle cx="23" cy="55" r="11" fill="#102c25"/><circle cx="90" cy="55" r="11" fill="#102c25"/></g></svg></div>`;
function render(){navigation();let title=page==='overview'?'A good day to go places.':page==='payments'?'Every payment, in view.':page==='team'?'Your people. Your permissions.':role==='customer'?'Your next journey awaits.':'Your booking desk.';$('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">RSS TRAVELS / ${role==='customer'?'CUSTOMER PORTAL':'BOOKING DESK'}</p><h1>${title}</h1><p class="subtitle">${role==='customer'?'Welcome, Aarav. Your trip details, all in one place.':'A little less paperwork. A lot more peace of mind.'}</p></div>${role!=='customer'&&page!=='team'?'<button class="primary" id="new-booking">＋ New booking</button>':''}</div>`;
if(page==='overview'){$('#content').innerHTML+=`<section class="hero"><div class="hero-copy"><p class="eyebrow">ON THE HORIZON</p><h2>Good journeys begin<br>with a little planning.</h2><p>You have <strong>${visible().filter(b=>['Pending','Confirmed'].includes(b.status)).length} upcoming trips</strong>. Let’s get them ready.</p></div>${art}</section>${stats()}<div class="section-head"><div><h2>Upcoming journeys</h2><p>Your next departures, at a glance.</p></div><button class="text-btn" id="view-all">All bookings →</button></div><div class="booking-grid">${visible().filter(b=>['Pending','Confirmed'].includes(b.status)).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4).map(card).join('')||'<div class="empty">No upcoming trips. Create your first booking.</div>'}</div>`;$('#view-all').onclick=()=>{page='bookings';render()}}
if(page==='bookings'||page==='payments'){if(page==='payments')$('#content').innerHTML+=stats();$('#content').innerHTML+=`${role==='customer'?'<p class="info">Customer preview: showing only Aarav’s sample bookings. Customers cannot change fares or record payments.</p>':''}<div class="tools"><input id="search" aria-label="Search bookings" placeholder="Search name, destination or booking ID…" value="${escape(query)}"><select id="filter" aria-label="Filter bookings">${['All','Confirmed','Pending','Completed','Cancelled'].map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="booking-grid" id="results"></div>`;results();$('#search').oninput=e=>{query=e.target.value;results()};$('#filter').onchange=e=>{filter=e.target.value;results()}}
if(page==='team')$('#content').innerHTML+=`<p class="info">Access design preview. Invitations and permission changes will work after we add secure login and the backend. Employees in this preview can create bookings and record payments.</p>${[['RS','You & your brother','All bookings, payments and access settings','Owners'],['EM','Booking employees','Create bookings · View bookings · Record payments','Employees'],['CU','Your customers','View their own trips and payment history','Customers']].map(([initial,name,desc,tag])=>`<div class="team-row"><span class="avatar">${initial}</span><div><h3>${name}</h3><p>${desc}</p></div><span class="badge">${tag}</span></div>`).join('')}`;
if($('#new-booking'))$('#new-booking').onclick=newBooking;bindDetails()}
function results(){const list=visible().filter(b=>(filter==='All'||b.status===filter)&&(page!=='payments'||(due(b)>0&&b.status!=='Cancelled'))&&`${b.name} ${b.from} ${b.to} ${b.id}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.date.localeCompare(b.date));$('#results').innerHTML=list.map(card).join('')||'<div class="empty">No bookings match this view.</div>';bindDetails()}
function openModal(html){$('#modal-body').innerHTML=html;$('#modal').showModal();$('#close-modal').onclick=()=>$('#modal').close()}
function modalHead(title){return `<div class="dialog-head"><h2>${title}</h2><button class="close" id="close-modal" aria-label="Close dialog">×</button></div>`}
function newBooking(){if(role==='customer')return;openModal(`${modalHead('Plan a new journey')}<p class="info">Use dummy details in this prototype. New bookings stay in this browser.</p><form id="booking-form"><div class="fields">${[['name','Customer name','text',true],['phone','Contact number','tel',true],['secondary','Secondary contact','tel',false],['car','Car','text',true],['from','Pickup location','text',true],['to','Drop location','text',true],['date','Travel date','date',true],['time','Pickup time','time',true],['purpose','Purpose','text',true],['total','Agreed fare (₹)','number',true],['advance','Advance received (₹)','number',true]].map(([name,label,type,required])=>`<label>${label}<input name="${name}" type="${type}" ${required?'required':''} ${type==='number'?'min="0" max="10000000" step="0.01"':''} ${type==='tel'?'pattern="[0-9+ ()-]{7,20}"':''} ${name==='advance'?'value="0"':''} maxlength="120"></label>`).join('')}<label>Advance payment mode<select name="mode"><option>UPI</option><option>Cash</option><option>Bank transfer</option></select></label></div><p class="error" id="form-error" role="alert"></p><div class="form-actions"><button type="submit" class="primary">Create booking →</button></div></form>`);$('#booking-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const total=Number(f.total),advance=Number(f.advance);if(['name','car','from','to','purpose'].some(k=>!f[k].trim())){$('#form-error').textContent='Please fill in each required field.';return}if(!Number.isFinite(total)||!Number.isFinite(advance)||advance>total){$('#form-error').textContent='Advance cannot be greater than the agreed fare.';return}const {advance:_,mode,...data}=f;bookings.push({...data,id:'RSS-'+Date.now().toString().slice(-8),customerId:'unlinked-'+Date.now(),total,status:'Confirmed',payments:advance?[{amount:advance,mode,date:new Date().toISOString().slice(0,10),by:role}]:[]});const persisted=save();$('#modal').close();render();if(persisted)toast('Booking saved in this browser') }}
function detail(id){const b=visible().find(b=>b.id===id);if(!b)return;openModal(`${modalHead(escape(b.id))}<span class="badge">${escape(b.status)}</span><h3>${escape(b.name)}</h3><div class="detail-route">${escape(b.from)} <span style="color:#96a97d">→</span><br>${escape(b.to)}</div><div class="detail-grid">${[['Departure',date(b.date)+' · '+b.time],['Car',b.car],['Purpose',b.purpose],['Contact',b.phone],['Agreed fare',money(b.total)],['Payments received',money(paid(b))]].map(([label,value])=>`<div><small>${label}</small><strong>${escape(value)}</strong></div>`).join('')}</div><div class="balance"><span>Remaining balance</span><strong>${money(due(b))}</strong></div><h3 style="font-size:14px">Payment history</h3>${b.payments.map(p=>`<div class="payment"><div>${escape(p.mode)}<small>${date(p.date)} · Recorded by ${escape(p.by)}</small></div><strong>${money(p.amount)}</strong></div>`).join('')||'<p class="subtitle">No payments recorded yet.</p>'}${role!=='customer'&&due(b)>0&&b.status!=='Cancelled'?`<form class="payment-form" id="payment-form"><h3>Record a payment</h3><label>Amount (₹)<input type="number" name="amount" min="0.01" max="${due(b)}" step="0.01" required></label><label>Payment mode<select name="mode"><option>UPI</option><option>Cash</option><option>Bank transfer</option></select></label><button class="primary wide" type="submit">Save payment</button></form>`:''}`);if($('#payment-form'))$('#payment-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),amount=Number(f.get('amount'));if(!Number.isFinite(amount)||amount<=0||amount>due(b))return;b.payments.push({amount,mode:f.get('mode'),date:new Date().toISOString().slice(0,10),by:role});const persisted=save();$('#modal').close();render();detail(id);if(persisted)toast('Payment recorded. Balance updated.') }}
$('#role').onchange=e=>{role=e.target.value;page=role==='customer'?'bookings':'overview';query='';filter='All';$('#modal').close();render()};
render();
